name: nakama
description: Nakama is an open-source scalable game server that lets you focus
  on building games.
version: 0.1.5
repository: https://github.com/obrunsmann/flutter_nakama
homepage: https://flutter-nakama.gitbook.io

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^4.0.1
  fixnum: ^1.0.0
  grpc: ^3.0.0
  json_annotation: ^4.0.1
  jwt_decoder: ^2.0.1
  logging: ^1.0.2
  meta: ^1.3.0
  protobuf: ^2.0.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.0.4
  chopper_generator: ^4.0.1
  faker: ^2.0.0
  flutter_lints: ^1.0.4
  json_serializable: ^4.1.3
  swagger_dart_code_generator: ^2.0.3
  test: ^1.17.5
