name: nakama
description: Nakama is an open-source scalable game server that lets you focus
  on building games.
version: 0.1.6
repository: https://github.com/obrunsmann/flutter_nakama
homepage: https://flutter-nakama.gitbook.io

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  chopper: ^5.1.0
  collection: ^1.16.0
  fixnum: ^1.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  grpc: ^3.1.0
  json_annotation: ^4.7.0
  jwt_decoder: ^2.0.1
  logging: ^1.1.0
  meta: ^1.8.0
  protobuf: ^2.1.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.2
  chopper_generator: ^5.1.0+1
  faker: ^2.0.0
  flutter_lints: ^2.0.1
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  swagger_dart_code_generator: ^2.8.5
  test: ^1.22.0
