name: satori
description: Satori is a liveops server for games that enables real-time event processing, player segmentation, and personalized messaging to enhance player engagement and retention.
version: 1.3.1
repository: https://github.com/heroiclabs/nakama-dart
homepage: https://heroiclabs.com/docs/nakama/client-libraries/dart

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.7.0
  freezed_annotation: ^3.0.0
  http: ^1.6.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  retrofit: '>=4.0.0 <5.0.0'
  
dev_dependencies:
  build_runner: ^2.5.4
  checked_yaml: ^2.0.4
  freezed: ^3.0.0
  json_serializable: ^6.9.5
  retrofit_generator: ^10.1.4
  test: ^1.26.2